### ISSUE TITLE
Add logic warnings for new fasta to fasta script if no. of autosomes is unequal in each haplotype

### ISSUE THREAD

**Issue by DomAbsolon** [sanger-tol/agp-tpf-utils#13]
Print a warning to stdout if the number of autosomes in each haplotype is unequal. Should be a warning and not an error because this may be a genuine biological situation or curation error.

**Comment by jgrg** [comment]
Resolved by https://github.com/sanger-tol/agp-tpf-utils/commit/d0684b2f922a8a4972b984d88227b7ee618f2718
