### ISSUE TITLE
Add logic warnings for new fasta to fasta script if whole chromosome is tagged as haplotig

### ISSUE THREAD

**Issue by DomAbsolon** [sanger-tol/agp-tpf-utils#14]
Add either an error or a warning message if a scaffold that is large enough to constitute the majority of a chromosome if tagged with the 'haplotig' metadata tag.

**Comment by jgrg** [comment]
Resolved by https://github.com/sanger-tol/agp-tpf-utils/commit/d0684b2f922a8a4972b984d88227b7ee618f2718
