### ISSUE TITLE
pyproject.toml build backend is missing the 'build_editable' hook

### ISSUE THREAD

**Issue by MboiTui** [sanger-tol/agp-tpf-utils#3]
Hello,

I tried following the steps in this repository to install the required environment to run the agp and tpf utilities, but I encountered the error:

`ERROR: Project file:///Users/lorenzo/Desktop/2024_PretextView/agp-tpf-utils has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.`

Below a screenshot of all the commands ran from `git clone` onwards

![Screen Shot 2024-08-23 at 4 39 49 pm](https://github.com/user-attachments/assets/bb4a2887-7827-4b28-80ba-3f30082e0d03)

**Comment by MboiTui** [comment]
I have ran `pip install --upgrade pip` and `pip install --upgrade setuptools` from within the environment, current versions are 21.3.1 for pip and 59.6.0 for setuptools. Nevertheless, the error persists.

Any help is appreciated

**Comment by yumisims** [comment]
@MboiTui  Thank you for raising this issue. I conducted a test but was unable to reproduce the error you encountered. I suggest upgrading setuptools using the following command: pip install --upgrade setuptools.
Additionally, we offer a Docker image that could help avoid dependency issues. You can find more information about the container here: https://github.com/sanger-tol/agp-tpf-utils/pkgs/container/agp-tpf-utils

Please let us know.
Thanks

**Comment by MboiTui** [comment]
Hello, 

Thank you for your suggestion. I tried upgrading wheel but the problem persists. Let me know what additional information I could provide to help you reproduce the issue.

```
pip install --upgrade wheel
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.37.1
```

```
pip install --editable .
Obtaining file:///Users/myusername/Desktop/myprojectfolder/agp-tpf-utils
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///Users/myusername/Desktop/myprojectfolder/agp-tpf-utils has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

In the mean time I will try using the docker image

Kind regards,
Lorenzo

**Comment by jgrg** [comment]
Hi Lorenzo,

The instructions for `pip install --editable` are in the README for developers. If you just want to install it, and don't need to edit the code, you can just do: `pip install .`

What version of Python do you have in your venv? (`python3 --version`)

James

**Comment by jgrg** [comment]
I _think_ you have an older version of Python. I developed the code on Python 3.10 and the version of `setuptools` in my venvs is 69 or greater, whereas you have setuptools 59.6.0
