### ISSUE TITLE
Dual curation pipeline 

### ISSUE THREAD

**Issue by Rhia15** [sanger-tol/agp-tpf-utils#5]
Hi, 

I was looking into the dual curation pipeline for pretext to assemble an autotetraploid, I noticed that I need the AGP_correct.py, and hap_split.py scripts, however I can't seem to find these scripts in this repository? I am just wondering if this has been removed or if I should be looking elsewhere? 

Thank you for any advice! :)

**Comment by jgrg** [comment]
Where did you see these scripts referenced?

**Comment by additive3** [comment]
@jgrg @Rhia15 

The hap_split.py script was one from Rockefeller. I don't know the repository, but I do know the person has since left.

**Comment by jgrg** [comment]
I don't know where to find out what these scripts do. What is the "dual curation pipeline"?
