### ISSUE TITLE
FASTA input and output in place of TPF & AGP format files

### ISSUE THREAD

**Issue by jgrg** [sanger-tol/agp-tpf-utils#6]
Use FASTA sequence data input instead of TPF. Current script used: `rapid_split.pl`

Creation of FASTA output rather than TPF, so that curators don't have to run another script, might be nice to save an AGP alongside the FASTA. Current scripts used: `rapid_join.pl` or `multi_join.py`

- `pretext-to-tpf` should take over naming of chromosomes.
- Generate an AGP file instead of a TPF.
  - Add mapping of PretextView scaffold numbers to chromosome names in AGP header

**Comment by yumisims** [comment]
Hi James, I'm not sure if this is the same issue that I addressed at the group meeting. I'd like the corrected AGP (based on the pretext AGP) to have the same autosome naming as the FASTA. Ideally, the pretext-to-tpf tool should take the pretext AGP and the correct autosome list and output the corrected AGP.

**Comment by jgrg** [comment]
No, that's different.

**Comment by jgrg** [comment]
Resolved by Release 1.1.0
